name: CI

on:
  push:
    branches: [master]
  pull_request: # run on all PRs, not just PRs to a particular branch

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - name: git clone
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 17.2.0
      - run: yarn
      - run: yarn build
      - run: yarn test
      # Fail if changes were written to any source files or generated untracked files.
      - run: git add -A && git diff --cached --exit-code
